#!/bin/bash
if [ -f $ENV_CONFIG ]; then
    source $ENV_CONFIG
fi

# # Updates cf-releases
# pushd /resources/cf-release
# git pull
# ./update
# popd

# pushd /resources/diego-release
# git pull
# ./scripts/update
# popd

# pushd /resources/garden-linux-release
# git pull
# popd

# go get -u all

/bin/bash