#! /bin/bash

if [[ -z "$BOSH_DIRECTOR" ]]
then
	echo 'INFO: Not Bosh director address found in variable BOSH_DIRECTOR.'
	echo 'Trying with a default bosh_lite installation...'
	echo -e "admin\nadmin\n" | bosh target 192.168.50.4 lite
	# bosh login admin admin 
else
	if [[ -z $BOSH_USER ]] || [[ -z $BOSH_USER ]]
	then 
		echo 'ERROR: Bosh credentials not found.'
		echo 'Please set up variables $BOSH_USER and $BOSH_PWD'
		exit 1
	fi 
	echo -e "$BOSH_USER\n$BOSH_PWD\n" | bosh target $BOSH_DIRECTOR
	# bosh login $BOSH_USER $BOSH_PWD
fi 
$*
